/**
 * Single asset-embedding script for the lansi skin. Reads the static assets
 * under `assets/` and emits the base64 data-URI modules consumed by
 * `src/client`. Regenerates:
 *   - src/client/background-art.generated.ts (illustrated background)
 *   - src/client/mascot-art.generated.ts     (pink-haired Q-version mascot)
 *   - src/client/ornament-art.generated.ts   (RPG sword / heart / flame icons)
 *   - src/client/frame-art.generated.ts      (inert crimson placeholders; the
 *                                             CSS uses solid crimson borders)
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const client = resolve(root, 'src', 'client')

// --- background (JPEG) ---
const bgBytes = readFileSync(resolve(root, 'assets', 'background', 'rance-35th-group.jpeg'))
const bgData = `data:image/jpeg;base64,${bgBytes.toString('base64')}`
writeFileSync(
  resolve(client, 'background-art.generated.ts'),
  `/* Generated by scripts/embed.mjs. */\n` +
    `export const ILLUSTRATED_BACKGROUND = ${JSON.stringify(bgData)} as const\n` +
    `export const SIDEBAR_CRIMSON_BACKGROUND = ${JSON.stringify(bgData)} as const\n`,
)

// --- mascot (PNG with alpha) ---
const mascotBytes = readFileSync(resolve(root, 'assets', 'mascot', 'rance-mascot.png'))
const mascotData = `data:image/png;base64,${mascotBytes.toString('base64')}`
writeFileSync(
  resolve(client, 'mascot-art.generated.ts'),
  `/* Generated by scripts/embed.mjs. */\n` +
    `export const PET_ART = ${JSON.stringify(mascotData)} as const\n`,
)

// --- ornaments (SVG) ---
const ornamentIds = ['sword-emblem', 'red-crest', 'sword', 'heart', 'flame', 'red-orb']
const camel = (id) => id.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())
const modes = ['light', 'dark']
const ornamentArt = Object.fromEntries(
  modes.map((mode) => [
    mode,
    Object.fromEntries(
      ornamentIds.map((id) => {
        const bytes = readFileSync(resolve(root, 'assets', 'ornaments', mode, `${id}.svg`))
        return [camel(id), `data:image/svg+xml;base64,${bytes.toString('base64')}`]
      }),
    ),
  ]),
)
const names = ornamentIds.map(camel)
writeFileSync(
  resolve(client, 'ornament-art.generated.ts'),
  `/* Generated by scripts/embed.mjs. */\n` +
    `export const ORNAMENT_IDS = ${JSON.stringify(names)} as const\n` +
    `export type OrnamentId = typeof ORNAMENT_IDS[number]\n` +
    `export type OrnamentMode = 'light' | 'dark'\n` +
    `export const ORNAMENT_ART = ${JSON.stringify(ornamentArt)} as const\n`,
)

// --- frames (inert crimson placeholders; CSS uses solid crimson borders) ---
const frameNames = ['selectedNav', 'composer', 'dialog', 'menu', 'panel', 'primaryButton']
const frameStroke = { light: '#c02a2a', dark: '#ff5a5a' }
const frameArt = Object.fromEntries(
  modes.map((mode) => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><rect x="1" y="1" width="14" height="14" rx="4" fill="none" stroke="${frameStroke[mode]}" stroke-width="2"/></svg>`
    const data = `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`
    return [mode, Object.fromEntries(frameNames.map((name) => [name, data]))]
  }),
)
writeFileSync(
  resolve(client, 'frame-art.generated.ts'),
  `/* Generated by scripts/embed.mjs. */\n` +
    `export const FRAME_IDS = ${JSON.stringify(frameNames)} as const\n` +
    `export type FrameId = typeof FRAME_IDS[number]\n` +
    `export type FrameMode = 'light' | 'dark'\n` +
    `export const FRAME_ART = ${JSON.stringify(frameArt)} as const\n`,
)

console.log('lansi assets embedded')
